### PR TITLE
feat: add support openapi 3.1

### PR DESCRIPTION
**Pull request by AlexVarchuk**
## What/Why/How?
Add support open API 3.1

Copied some changes back from https://github.com/stoplightio/json-schema-sampler

cc @P0lip

## Check yourself

- [x] Code is linted
- [x] Run test
- [x] All new/updated code is covered with tests

### CODE REVIEW

**Review by RomanHotsiy — APPROVED** [review]

**Comment by philsturgeon** [comment]
Hey folks! This was a bit of a surprise, as we would have been happy to help you merge these changes back. The way this is done there's no attribution, no commit history, and seemingly no thank you anywhere.

We love attributing our friends working on API tooling at other organizations, like this on [elements](https://github.com/stoplightio/elements): 

Screen Shot 2021-05-25 at 11 03 08 AM

If you'd like to do something similar, or pull the commits directly so @P0lip gets the history, that would be cool. If you plan on saying thanks elsewhere then no worries, this just felt like a bit of a shock to us as it's very non-standard for OSS projects to work this way.

**Comment by RomanHotsiy** [comment]
@philsturgeon 

Oh, we didn't meant to do it this way. I apologize for that.
You proposed I help merge these changes a few months ago. We did not want to bother you with that and decided to do it ourselves to save your time.

I agree it would be better to pull @Polip commits directly. But we did not copy it 1-1, we had to add some minor changes to support backward-compatibility with our tools. I've rebased the history by pulling @Polip commits and then adding our changes on top and will add attribution to the readme.

I apologize again for this whole situation.

On the other hand, this is also non-standard in OSS to fork-rename (and change the author) without first trying to contribute the changes to the source project. We understand you probably needed it ASAP and did not want to wait for us to review the PR.

**Comment by philsturgeon** [comment]
Yeah that’s the reason for the fork, we also renamed it to make it clear it’s focused on JSON schema now not just openapi; which you might want to also do now that the two specs have merged. It was “so this, get on with it, see if we can get things upstream later”

I understand the motivations, and respect that you didn’t mean or do anything in bad faith, but this makes our fork a little harder to reconcile and close down it’s diverged from or history. If it’s got the same functionality and similar enough hopefully we can just ditch ours.

**Comment by RomanHotsiy** [comment]
Yes, it's the same functionality from what I can tell. You should be able to use it.

If something is missing, a PR would be appreciated! It shouldn't get ages to get merged 😄

**Comment by philsturgeon** [comment]
Cheers folks, stay safe and happy! Looking forward to another beer at a conference when we're aloud to do all that again. 👋🏻

**Pull request merged**
